#!/bin/bash

LOG_FILE="${TRIM_PKGVAR}/info.log"
PID_FILE="${TRIM_PKGVAR}/app.pid"

# write the command to start your program here
CMD=""

log_msg() {
  echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >>${LOG_FILE}
}

start_process() {
  if status; then
    return 0
  fi

  log_msg "Starting process ..."
  systemctl start open-vm-tools.service >>${LOG_FILE} 2>&1
}

stop_process() {
  log_msg "Stopping process ..."

  systemctl stop open-vm-tools.service >>${LOG_FILE} 2>&1
}

status() {
  systemctl status open-vm-tools.service
}

case $1 in
  start)
    # run start command. exit 0 if success, exit 1 if failed
    if [ ! -e /dev/vmci ]; then
      SYS_LANGUAGE="${TRIM_SYS_LANGUAGE:-}"
      case "${SYS_LANGUAGE,,}" in
        zh[-_]cn)
          MSG="未找到 QEMU Guest Agent 设备，无法启动。"
          ;;
        *)
          MSG="VMware VMCI device not found. Cannot start."
          ;;
      esac
      echo "${MSG}" >"$TRIM_TEMP_LOGFILE"
      exit 1
    fi
    start_process
    ;;
  stop)
    # run stop command. exit 0 if success, exit 1 if failed
    stop_process
    ;;
  status)
    # check application status command. exit 0 if running, exit 3 if not running
    if status; then
      exit 0
    else
      exit 3
    fi
    ;;
  *)
    exit 1
    ;;
esac
