#!/bin/bash

### This script is called before the user installs the application.

curl -kL https://github.com/tsl0922/ttyd/releases/latest/download/ttyd.$(uname -m) -o /usr/bin/ttyd
chmod +x /usr/bin/ttyd 2>/dev/null
[ ! -x /usr/bin/ttyd ] && exit 1

apt update
apt install -y --no-install-recommends tmux

exit $?
